export const GENRES = [
    "All",
    "Pop",
    "Rock",
    "Hip Hop",
    "Electronic",
    "Jazz",
    "Classical",
    "R&B",
    "Country",
    "Metal",
    "Folk",
    "Blues",
    "Reggae",
    "World",
    "Experimental",
    "Ambient",
    "Lo-fi",
    "Synthwave",
    "House",
    "Techno",
    "Drum & Bass",
    "Dubstep",
    "Trap",
    "Future Bass",
    "Chillwave",
] as const

export const MOODS = [
    "All",
    "Happy",
    "Sad",
    "Energetic",
    "Relaxed",
    "Aggressive",
    "Melancholic",
    "Uplifting",
    "Dark",
    "Playful",
    "Mysterious",
    "Romantic",
    "Nostalgic",
    "Dreamy",
    "Epic",
    "Intense",
    "Calm",
    "Funky",
    "Groovy",
    "Soulful",
] as const

export const INSTRUMENTS = [
    "All",
    "Vocals",
    "Guitar",
    "Bass",
    "Drums",
    "Piano",
    "Synth",
    "Saxophone",
    "Violin",
    "Trumpet",
    "Flute",
    "Clarinet",
    "Harp",
    "Organ",
    "Accordion",
    "Banjo",
    "Mandolin",
    "Ukulele",
    "Harmonica",
    "Tambourine",
] as const

export const KEY_SIGNATURES = [
    "C",
    "G",
    "D",
    "A",
    "E",
    "B",
    "F#",
    "C#",
    "F",
    "Bb",
    "Eb",
    "Ab",
    "Db",
    "Gb",
    "Cb",
    "Am",
    "Em",
    "Bm",
    "F#m",
    "C#m",
    "G#m",
    "D#m",
    "A#m",
    "Dm",
    "Gm",
    "Cm",
    "Fm",
    "Bbm",
    "Ebm",
    "Abm",
] as const

export const TIME_SIGNATURES = [
    "4/4",
    "3/4",
    "6/8",
    "2/4",
    "5/4",
    "7/8",
    "12/8",
    "9/8",
    "2/2",
    "3/2",
] as const

// Type definitions for the constants
export type Genre = typeof GENRES[number]
export type Mood = typeof MOODS[number]
export type Instrument = typeof INSTRUMENTS[number]
export type KeySignature = typeof KEY_SIGNATURES[number]
export type TimeSignature = typeof TIME_SIGNATURES[number] 